#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - git
  - docker.io
  - docker-compose-v2

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker azureuser
  - git clone https://github.com/MaksymZolotarchuk/docker-data-pipeline.git /home/azureuser/app
  # Запуск основного додатку
  - cd /home/azureuser/app
  - docker compose up -d
  # Запуск моніторингу
  - cd /home/azureuser/app/monitoring
  - docker compose -f docker-compose.monitoring.yml up -d
