apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: my-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_VERSION
          value: "1.0"
