apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: lab-namespace
spec:
  type: NodePort
  selector:
    app: my-web-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
